import type { Metadata } from "next";
import "./globals.css";
import { bricolage, kalnia } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bricolage.variable} ${kalnia.variable} antialiased`}
      >
        <section className="flex flex-col items-center justify-center max-w-[1400px] mx-[100px]">
          {children}
        </section>
      </body>
    </html>
  );
}
